name: step
description: Manage Bitrise CLI steps
executable:
  osx: https://github.com/bitrise-io/bitrise-plugins-step/releases/download/0.10.3/bitrise-plugins-step-Darwin-x86_64
  osx-arm64: https://github.com/bitrise-io/bitrise-plugins-step/releases/download/0.10.3/bitrise-plugins-step-Darwin-arm64
  linux: https://github.com/bitrise-io/bitrise-plugins-step/releases/download/0.10.3/bitrise-plugins-step-Linux-x86_64
trigger: ""
requirements:
- tool: bitrise
  min_version: 1.3.0
  max_version: ""
